[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'  # Match .py and .pyi files

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[flake8]
max-line-length = 88
exclude = '.git,__pycache__,venv'
max-complexity = 10
