name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests and Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run Black code formatter
      run: black --check .
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Check import sorting with isort
      run: isort --check-only .
    
    - name: Run security checks with Bandit
      run: bandit -r . -x ./venv
    
    - name: Check for insecure dependencies
      run: safety check --full-report
    
    - name: Run static type checking with mypy
      run: mypy --ignore-missing-imports .
    
    - name: Check docstring style with pydocstyle
      run: pydocstyle .
    
    - name: Run tests with pytest and coverage
      run: |
        pytest --cov=. --cov-report=xml
        python -m coverage report --fail-under=80
    
    - name: Test application endpoints
      run: |
        # Start the Flask app in the background
        python app.py &
        # Give the app time to start
        sleep 5
        # Test the health endpoint
        curl --fail http://localhost:5001/health
    
    - name: Setup pre-commit hooks
      run: |
        pre-commit install
        pre-commit run --all-files
  
  # Deployment job has been removed
  # To add deployment in the future, create a new job with the necessary steps