name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Check code formatting with Black
      run: black --check .
      
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Check import sorting with isort
      run: isort --check-only .
    
    - name: Run security checks with Bandit
      run: bandit -r . -x ./venv
    
    - name: Check for insecure dependencies
      run: safety check --full-report
    
    - name: Run static type checking with mypy
      run: mypy --ignore-missing-imports .
    
    - name: Check docstring style with pydocstyle
      run: pydocstyle .
    
    - name: Run tests with pytest and coverage
      run: |
        pytest --cov=. --cov-report=xml
        python -m coverage report --fail-under=80
    
    - name: Run application tests
      run: |
        # Start the Flask app in the background
        python app.py &
        # Give the app time to start
        sleep 5
        # Test the health endpoint
        curl --fail http://localhost:5001/health
    
    - name: Setup pre-commit hooks
      run: |
        pre-commit install
        pre-commit run --all-files
  
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | bash
      
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku --version
          heroku container:login
          heroku container:push web -a $HEROKU_APP_NAME
          heroku container:release web -a $HEROKU_APP_NAME