name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8 isort
        
    - name: Check code formatting with Black
      run: |
        black --check .
        
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=88 --statistics
        
    - name: Check import sorting with isort
      run: |
        isort --check-only .
        
    - name: Run tests
      run: |
        # Start the Flask app in the background
        python app.py &
        # Give the app time to start
        sleep 5
        # Test the health endpoint
        curl --fail http://localhost:5001/health